# Project information
site_name: IKS Cloud Native Workshop
site_url: https://jrtorres.github.io/iks-cloudnativeworkshop
site_author: Javier Torres

# Repository
repo_name: iks-cloudnativeworkshop
repo_url: https://jrtorres.github.io/iks-cloudnativeworkshop
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - Workshop Overview: README.md
  - Environment Setup:
    #- Setup: generatedContent/workshop-setup/docs/README.md
    #- Register for IBM Cloud: generatedContent/workshop-setup/docs/NEWACCOUNT.md
    - Grant Kubernetes Cluster: generatedContent/workshop-setup/docs/GRANTCLUSTER.md
    #- IBM Cloud Shell: generatedContent/workshop-setup/docs/CLOUDSHELL.md
    #- Terminal at CognitiveClass.ai: generatedContent/workshop-setup/docs/COGNITIVECLASS.md
    #- Helm v3: generatedContent/workshop-setup/docs/HELM.md
    - Cloud Shell: pre-work/README.md
  - Kube 101:
    #- Lab 0. Access a Kubernetes cluster: generatedContent/kube101/Lab0/README.md
    - Lab 1. Deploy your first application: generatedContent/kube101/Lab1/README.md
    - Lab 2. Scale and update deployments: generatedContent/kube101/Lab2/README.md
    - Lab 3. Build multi-tier applications: generatedContent/kube101/Lab3/README.md
  - Helm 101:
    #- Lab 0. Installing Helm on IKS: generatedContent/helm101/Lab0/README.md
    - Lab 1. Deploy with Helm: generatedContent/helm101/Lab1/README.md
    - Lab 2. Make changes with Helm: generatedContent/helm101/Lab2/README.md
    - Lab 3. Keeping track of the deployed application: generatedContent/helm101/Lab3/README.md
    - Lab 4. Share Helm Charts: generatedContent/helm101/Lab4/README.md
  - Jenkins 101:
    - Jenkins and Kubernetes: generatedContent/jenkins101/README.md
  - Microservices:
    - Lab 1. Deploy Microservices Application: generatedContent/deploy-microservices/README_deployment.md    
  - Storage:
    - Kubernetes Storage: generatedContent/kubernetes-storage/README.md
    - Lab 1. Container/Pod/Node storage and Kubernetes: generatedContent/kubernetes-storage/Lab1/README.md
    - Lab 2. File storage with kubernetes: generatedContent/kubernetes-storage/Lab2/README.md
    - Lab 3. Block storage with kubernetes: generatedContent/kubernetes-storage/Lab3/README.md    
  - Operators:
    - Kubernetes Operators: generatedContent/kubernetes-operators/README.md
    - Lab 1. Custom Resource (CR): generatedContent/kubernetes-operators/lab1.md
    - Lab 2. Operator from Helm: generatedContent/kubernetes-operators/lab3.md
  - Istio 101:
    - Lab 1. Setup: generatedContent/istio101/exercise-1/README.md
    - Lab 2. Install Istio: generatedContent/istio101/exercise-2/README.md
    - Lab 3. Deploy Guestbook App: generatedContent/istio101/exercise-3/README.md
    - Lab 4. Traffic Management: generatedContent/istio101/exercise-6/README.md
    - Lab 5. mutual TLS: generatedContent/istio101/exercise-7/README.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2020 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.indexes
  palette:
    scheme: default
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper
  version:
    method: mike

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
